cleanmodel:
	@rm -f	*.dat *.out *.info *.used                           \
	   wavelength_micron.inp dustopac.inp dust_density.inp      \
	   amr_grid.inp stars.inp radmc.inp
	@echo All .out files and most .inp files removed.

cleanall:
	@rm -f	*.o *.mod *.dat *.out *.info *.used                 \
	   wavelength_micron.inp dustopac.inp dust_density.inp      \
	   amr_grid.inp stars.inp radmc.inp image_script.pro        \
	   radmc3d Makefile~ *.pro~ README*~ *.f90~ *.inp~
	@echo Directory cleaned to basic
