cleanmodel:
	@rm -f	*.o *.mod *.used                                    \
	   *wavelength_micron.inp dustopac.inp                      \
	   dust_density.uinp *.uout *.udat                          \
	   stars.inp radmc3d.inp envstruct.*                        \
	   dustopac*.inp transphere.inp starinfo.inp                \
	   frequency_hz.inp stellarsrc_*.inp heatsource.inp
	@echo All .o, .mod, .out files and most .inp files removed.

cleanall:
	@rm -f	*.o *.mod *.pyc *.used                              \
	   *wavelength_micron.inp dustopac.inp                      \
	   dust_density.uinp *.uout *.udat                          \
	   stars.inp radmc3d.inp image_script.pro                   \
	   radmc3d Makefile~ *.pro~ README*~ *.f90~ *.inp~ *.py~    \
	   envstruct.* dustopac*.inp transphere.inp  starinfo.inp   \
	   frequency_hz.inp stellarsrc_*.inp heatsource.inp
	@echo Directory cleaned to basic, but leaving main test results
