cleanmodel:
	@rm -f	*.o *.mod *.dat *.out *.info *.used                 \
	   *wavelength_micron.inp dustopac.inp dust_density.inp     \
	   dust_density.uinp *.uout *.udat                          \
	   amr_grid.inp stars.inp radmc3d.inp envstruct.*           \
	   dustopac*.inp transphere.inp starinfo.inp                \
	   frequency_hz.inp
	@echo All .o, .mod, .out files and most .inp files removed.

cleanall:
	@rm -f	*.o *.mod *.pyc *.dat *.out *.info *.used           \
	   *wavelength_micron.inp dustopac.inp dust_density.inp     \
	   dust_density.uinp *.uout *.udat                          \
	   amr_grid.inp stars.inp radmc3d.inp image_script.pro      \
	   radmc3d Makefile~ *.pro~ README*~ *.f90~ *.inp~ *.py~    \
	   envstruct.* dustopac*.inp transphere.inp  starinfo.inp   \
	   frequency_hz.inp
	@echo Directory cleaned to basic
